/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FrontRouteImport } from './routes/_front'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FrontIndexRouteImport } from './routes/_front.index'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminExperiencesRouteImport } from './routes/admin/experiences'
import { Route as AdminEducationRouteImport } from './routes/admin/education'
import { Route as AdminComponentsRouteImport } from './routes/admin/components'
import { Route as AdminAboutRouteImport } from './routes/admin/about'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontRoute = FrontRouteImport.update({
  id: '/_front',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FrontIndexRoute = FrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperiencesRoute = AdminExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEducationRoute = AdminEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComponentsRoute = AdminComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/components': typeof AdminComponentsRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/': typeof FrontIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/admin/about': typeof AdminAboutRoute
  '/admin/components': typeof AdminComponentsRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/': typeof FrontIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_front': typeof FrontRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/components': typeof AdminComponentsRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/_front/': typeof FrontIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/about'
    | '/admin/components'
    | '/admin/education'
    | '/admin/experiences'
    | '/admin/hero'
    | '/admin/projects'
    | '/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/about'
    | '/admin/components'
    | '/admin/education'
    | '/admin/experiences'
    | '/admin/hero'
    | '/admin/projects'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/_front'
    | '/admin'
    | '/admin/about'
    | '/admin/components'
    | '/admin/education'
    | '/admin/experiences'
    | '/admin/hero'
    | '/admin/projects'
    | '/_front/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FrontRoute: typeof FrontRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front': {
      id: '/_front'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_front/': {
      id: '/_front/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontIndexRouteImport
      parentRoute: typeof FrontRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences': {
      id: '/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminExperiencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/education': {
      id: '/admin/education'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminEducationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/components': {
      id: '/admin/components'
      path: '/components'
      fullPath: '/admin/components'
      preLoaderRoute: typeof AdminComponentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface FrontRouteChildren {
  FrontIndexRoute: typeof FrontIndexRoute
}

const FrontRouteChildren: FrontRouteChildren = {
  FrontIndexRoute: FrontIndexRoute,
}

const FrontRouteWithChildren = FrontRoute._addFileChildren(FrontRouteChildren)

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminComponentsRoute: typeof AdminComponentsRoute
  AdminEducationRoute: typeof AdminEducationRoute
  AdminExperiencesRoute: typeof AdminExperiencesRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminComponentsRoute: AdminComponentsRoute,
  AdminEducationRoute: AdminEducationRoute,
  AdminExperiencesRoute: AdminExperiencesRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FrontRoute: FrontRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
